# [toolchain]
# channel = "stable"

# For rust-gpu, fix the toolchain to this specific nightly
[toolchain]
channel = "nightly-2024-11-22"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = b19329a37cedf2027517ae22c87cf201f93d776e
