[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
glam = { workspace = true }

[target.'cfg(target_arch = "spirv")'.dependencies]
spirv-std = { workspace = true }